version: "3.3"
services:

  nats:
    image: nats-streaming:latest
    hostname: nats
    volumes:
      - '../../datastore:/datastore'
      - './nats.config:/nats.config'
    command: ["-sc", "./nats.config"]
    networks:
      - hpndev
  
  exec:
    build: ./
    volumes:
      - '../../:/home'

    command: ["bash", "-c", "${FILE}"]

    ipc: host
    shm_size: 4GB
    depends_on:
      - nats
    networks:
      - hpndev

  

networks:
  hpndev:

