version: "3.3"
services:

  nats:
    image: nats-streaming:latest
    hostname: nats
    volumes:
      - './datastore:/datastore'
      - './docker/dev/nats.config:/nats.config'
    command: ["-sc", "./nats.config"]
    networks:
      - hpndev
      
  redis:
    image: redis
    hostname: redis
    networks:
      - hpndev

  exec:
    build: ./docker/dev/
    volumes:
      - './:/home'
    command: ["bash", "-c", "${FILE}"]
    ipc: host
    shm_size: 4GB
    depends_on:
      - nats
      - redis
    networks:
      - hpndev

  tests:
    build: ./docker/dev/
    volumes:
      - './:/home'
    command: ["node", "./tests/unit"]
    depends_on:
      - nats
      - redis
    networks:
      - hpndev

  

networks:
  hpndev:

